language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - main
script:
  - cd ./WebApp
  - npm install -g @angular/cli
  - ng lint
  - ng build --prod --base-href https://github.com/KeithMarex/VvE-APP/tree/main/WebApp
