language: node_js
node_js:
  - "15"
dist: trusty
sudo: required
branches:
  only:
    - main
script:
  - cd ./WebApp
  - npm install -g @angular/cli
  - npm install --save
  - ng lint
  - ng build --prod
