language: node_js
node_js:
  - "15"
dist: trusty
sudo: required
branches:
  only:
    - main
script:
# Script voor API
  - cd ./API
  - npm install --save
  - npm test

# Script voor WebApp
  - cd ./WebApp
  - npm install -g @angular/cli
  - npm install --save
  - ng build --prod
