openapi: 3.0.0
info:
  title: VvE Api
  description: This api serves the vve applications (Mobile and web)
  version: 1.0.0
tags:
  - name: User
  - name: Tag
  - name: Ticket

paths:
  /user/{id}:
    $ref: ./user/getUser.yaml
  /user/login:
    $ref: ./user/login.yaml
  /user/register:
    $ref: ./user/register.yaml
  /tag:
    $ref: ./tag/getTags.yaml
  /tag/{id}:
    $ref: ./tag/getTag.yaml
  /tag/:
    $ref: ./tag/postTag.yaml