openapi: 3.0.0
info:
  title: VvE Api
  description: This api serves the vve applications (Mobile and web)
  version: 1.0.0
tags:
  - name: User
  - name: Tag
  - name: Ticket
  - name: Comment
  - name: Agenda

paths:
  /user:
    $ref: ./user/getUsers.yaml
  /user/{id}:
    $ref: ./user/getUser.yaml
  /user/login:
    $ref: ./user/login.yaml
  /user/register:
    $ref: ./user/register.yaml
  /user/organization/{id}:
    $ref: ./user/getUserOrganization.yaml
  /tag:
    $ref: ./tag/getTags.yaml
  /tag/{id}:
    $ref: ./tag/getTag.yaml
  /tag/:
    $ref: ./tag/postTag.yaml
  /tag/{id}/:
    $ref: ./tag/putTag.yaml
  /tag/{id}//:
    $ref: ./tag/deleteTag.yaml
  /ticket:
    $ref: ./ticket/getTickets.yaml
  /ticket/{id}:
    $ref: ./ticket/getTicket.yaml
  /ticket/:
    $ref: ./ticket/postTicket.yaml
  /ticket/{id}/:
    $ref: ./ticket/putTicket.yaml
  /ticket/{id}//:
    $ref: ./ticket/deleteTicket.yaml
  /comment/:
    $ref: ./comment/postComment.yaml
  /agenda/{month}/:
    $ref: ./agenda/getAgenda.yaml
  /agenda/:
    $ref: ./agenda/postAgenda.yaml
  /agenda/{id}/:
    $ref: ./agenda/putAgenda.yaml
  /agenda/{id}//:
    $ref: ./agenda/deleteAgenda.yaml